### ISSUE TITLE
API key can't be set

### ISSUE THREAD

**Issue by sangdrax8** [puzzle/puzzle.opnsense#126]
**Describe the bug**
You take a list of strings for setting an API key, but this isn't a list of dictionaries.  Therefore one can not pass in both the key and the secret, which would be required to set a known functioning key.  In fact, what it does now is somewhat destructive.  This module will set the given key, while generating a new secret for it.  This will cause the expected key to have a now unknown to the user secret.  If the user tried to pass in both key and secret in the list, they would just get 2 new keys, neither of which they know.

**To Reproduce**
1. take an existing key/secret pair
2. attempt to set this key with the module

**Expected behavior**
An API can be set to an exact known key/secret.  It would be nice if the api list was a list of dictionaries.  Much like you generate.  This way the user could pass in 
```
api_key:
  - key=XXXX
    secret=YYYY
  - key=AAAA
    secret=BBBB
```

**Environment**
 - puzzle.opnsense virtualbox image
 - molecule
 - ansible 2.16

**Additional context**
This would be really useful for molecule, as I could hard code a "testing" key/secret pair in my molecule inventory.  Then have my role deploy this key only in a molecule instance.  This would allow me to use the API (or ansibleguys modules) in molecule with out any manual intervention to update the API key/secret every time I bring it up.

**Comment by KiLLuuuhh** [comment]
Hello @sangdrax8 

Thank you for taking the time and contribute to this project.

Your absolutely right about this, we will fix this with the next release.
