### ISSUE TITLE
Minmal Module & Module Development Guide

### ISSUE THREAD

**Issue by DonGiovanni83** [puzzle/puzzle.opnsense#14]
**Is your feature request related to a problem? Please describe.**
The collection is now ready for the first module. At the same time, we need to document a guide for developers on how modules should be implemented in the collection.

**Describe the solution you'd like**
A simple module with a minimalistic and straightforward functionality like the one described in issue #13 should be implemented. A module development guide must be written to the doc site as well, where the development workflow etc. are described. 

**Describe alternatives you've considered**
No alternatives were considered. Open for suggestions on what feature is best suited for the mentioned simple/minimal module.

**Additional context**
 - Read #13 carefully for context on the module to implement
 - Read the development guide on how to use the `OPNsenseConfig` class.

**Comment by acteru** [comment]
#17

**Comment by DonGiovanni83** [comment]
Resolved by #17
