### ISSUE TITLE
module to set hostname and domain

### ISSUE THREAD

**Issue by rekup** [puzzle/puzzle.opnsense#19]
**Is your feature request related to a problem? Please describe.**
This is a feature request to create the first module which should be able to set the hostname and domain (System -> Settings -> General

**Describe the solution you'd like**
The module should be able to configure the hostname and the domain of an opnsense instance. The naming will be as defined in https://github.com/puzzle/puzzle.opnsense/issues/13#issue-1822510592

**Comment by DonGiovanni83** [comment]
Since we have those features since #21 inside the [`system_settings_general`](https://puzzle.github.io/puzzle.opnsense/collections/puzzle/opnsense/system_settings_general_module.html#ansible-collections-puzzle-opnsense-system-settings-general-module) module, I am going to close this issue.
