### ISSUE TITLE
Module Request: password

### ISSUE THREAD

**Issue by ombre8** [puzzle/puzzle.opnsense#50]
### Module Description

Change the password of the currently logged-in user via the Lobby:

![2024-03-21-101543_956x441_scrot](https://github.com/puzzle/puzzle.opnsense/assets/2480918/4dc3c40e-6c87-4e67-ad42-0f3fe77c9ca1)

### Additional Notes (Optional)

* As we are able to change the Password of all Users via the `system_access_users` module, it does not make any sense to implement an Ansible module to change the Password of a currently logged in User
* This Issue can be closed when #42 is implemented

**Comment by KiLLuuuhh** [comment]
Since https://github.com/puzzle/puzzle.opnsense/pull/42 is merged, I am closing this issue.
